### ISSUE TITLE
log to file does not work

### ISSUE THREAD

**Issue by spo0lsh** [isc-projects/bind9-docker#2]
"not using config file logging statement for logging due to -g option" when start docker container from [instructions](https://hub.docker.com/_/bind9/plans/3af94cc6-b9c6-43c2-8658-e617ef977949?tab=instructions):

```
docker run \
        --name=bind9 \
        --restart=always \
        --publish 53:53/udp \
        --publish 53:53/tcp \
        --publish 127.0.0.1:953:953/tcp \
        --volume /etc/bind \
        --volume /var/cache/bind \
        --volume /var/lib/bind \
        --volume /var/log \
        internetsystemsconsortium/bind9:9.16
```

**Comment by j-pro-git** [comment]
I still see this error using BIND 9.18. The reason is that named is run with the -g option (as the error message suggests). The manual page says that means "Run the server in the foreground and force all logging to _stderr_."
The issue and a potential fix have been extensively discussed at [ventz/docker-bind/issues/32](https://github.com/ventz/docker-bind/issues/32#issuecomment-586344212). I guess it would be helpful to apply a similar change here.
