### ISSUE TITLE
Version '1:9.18.11-1+ubuntu22.04.1+isc+2' for 'bind9' was not found

### ISSUE THREAD

**Issue by a254719421** [isc-projects/bind9-docker#8]
Hi,I＇m using Bind Dockerfile 9.18,but while I was building mirroring,I found that the repo resource doesn't include 9.18.11-1+ubuntu22.04.1+isc+2 and isc+1.

when I try to build the image

 => [internal] load metadata for docker.io/library/ubuntu:jammy                                                                                                                     
 > [ 8/14] RUN apt-get -qqqy install bind9=1:9.18.11-1+ubuntu22.04.1+isc+2 bind9utils=1:9.18.11-1+ubuntu22.04.1+isc+2:
**#0 0.750 E: Version '1:9.18.11-1+ubuntu22.04.1+isc+2' for 'bind9' was not found
#0 0.750 E: Version '1:9.18.11-1+ubuntu22.04.1+isc+2' for 'bind9utils' was not found**
Dockerfile:20
  18 |     RUN apt-get -qqqy update
  19 |     RUN apt-get -qqqy dist-upgrade
  20 | >>> RUN apt-get -qqqy install bind9=$DEB_VERSION bind9utils=$DEB_VERSION
  21 |     
  22 |     # Now remove the pkexec that got pulled as dependency to software-properties-common
error: failed to solve: process "/bin/sh -c apt-get -qqqy install bind9=$DEB_VERSION bind9utils=$DEB_VERSION" did not complete successfully: exit code: 100
FATA[0001] no image was built

**Comment by oerdnj** [comment]
This is an internal project for building the images and you should be using pre-built images. Especially, when you can't fix simple issues like these yourself.

I am going to fix this now because I need to update the libuv1 package in the pre-built images, but my recommendation for you is to use the pre-built packages if you can't fix the basics yourself.
